### ISSUE TITLE
Voxel Size

### ISSUE THREAD

**Issue by andrewtheone** [andyhall/noa#10]
What should i tweak to resize voxels? (all of them, lets say make them 0.25*0.25*0.25 unit instead of 1*1*1)

**Comment by andyhall** [comment]
Hey, sorry for the consistently late replies.

For voxel size, there is no built-in way currently. I experimented with this some, and I wound up not putting in a scaling factor because, as near as I can tell, voxel size is essentially a matter of camera position and settings. That is, if the camera is about 1.6 voxels off the ground then the voxels appear Minecraft-sized, but if you set the player height to 5 voxels, and maybe change the FOV, then effectively the world is now made up of much smaller voxels. Since there's nothing in the world except voxels and the player, making the voxels smaller is the same as making the player bigger, does that make sense?

Anyway if you want to try hacking on it, you could try scaling the actual vertex positions as they are written into the voxel mesh, [here](https://github.com/andyhall/noa/blob/master/lib/chunk.js#L544-L547). However I'm sure there are a bunch of other things that would need to be fixed, and I'm not quite sure how many.

**Comment by JaegerBomBYT** [comment]
how do we go about changing the fov?

**Comment by fenomas** [comment]
@JaegerBomBYT This engine uses Babylon.js internally, so most non-voxel customizations are done by changing babylon object properties. In this case, babylon cameras have an ["fov"](https://doc.babylonjs.com/typedoc/classes/BABYLON.Camera#fov) property, and by default `noa` stores its camera at `noa.rendering.camera`, so you can do something like this to change the fov:

```js
noa.rendering.camera.fov = 0.5
```
