### ISSUE TITLE
How to texture blocks with images?

### ISSUE THREAD

**Issue by johno1566** [andyhall/noa#107]
I feel stupid asking this, but when I try to texture a block using the image url in the example files I get this:
![image](https://user-images.githubusercontent.com/32988429/80996974-8bca0d00-8df5-11ea-9296-d19af3972781.png)

**Comment by andyhall** [comment]
Hi, I'm not sure but I think that's Babylon's "texture not found" texture, so my first guess would be something mundane like a typo in the image url path, or maybe something with webpack settings related to paths? If you check the browser's dev console there may be errors showing what path was loaded.

Alternately, if you try running the test world (with `npm test` rather than `npm start` in the examples repo), there are some textured blocks in that world which should hopefully be a reference!

**Comment by johno1566** [comment]
Ahhh, I found my issue. Turns out you have to put the Assets in the docs/helloworld folder. I should've read console.
