### ISSUE TITLE
Customized cameras and physics backtracking

### ISSUE THREAD

**Issue by terrac** [andyhall/noa#114]
I'm getting a small amount of shakiness when I implement a custom camera 

I'm overriding the function at g.camera.updateBeforeEntityRenderSystems
and using
g.ents.setPosition(g.camera.cameraTarget,cameraPos)

I'm thinking that somehow this and physics backtracking don't match.  I'm wondering if there is anything obvious I am doing wrong

Thanks

**Comment by andyhall** [comment]
Hi, yes that definitely sounds like temporal aliasing due to the physics backtracking not lining up with the camera's motion. If you drive your camera by having it tied to a physics entity (which you move around with forces and impulses), I'd guess that should fix it.  But if you want to move the camera arbitrarily by some other logic, you'll need to do your own backtracking [similar to this](https://github.com/andyhall/noa/blob/fee098e3f7d4145ea982acf8cafc2f543a85d46f/src/components/physics.js#L94).

**Comment by terrac** [comment]
Attaching a physics entity worked pretty well.
