### ISSUE TITLE
Custom objects

### ISSUE THREAD

**Issue by andrewtheone** [andyhall/noa#2]
I'd use noa engine for a personal project where I have to load more than 200-300 different textures, depending on player positions (there would be rooms, and in each room there are pictures like a galery).

My question is, does the engine only loads the textures if they are visible, or they'll load anyways? and plus question: does custom meshes only rendered/added to the scene to the position when they'd appear on the scene?

**Comment by andyhall** [comment]
Hey, glad to hear it and I hope the project is useful.

Very generally, the goal of this engine is to abstract away some complexities of dealing with voxels (chunking, meshing, raycasting, etc), and not do too much else. So for anything that's not a voxel, stuff like loading or unloading assets is mostly down to the 3D engine.

With that said, by custom meshes you mean voxels that use a user-defined mesh instead of a square, right? If so, then here's how things work currently: to define an object mesh, you create it and noa saves a copy, but it's not added to the scene. At this point I'd imagine any related textures are in browser memory but not in GPU memory. Then once the scene begins, noa creates and renders all voxels within a certain range of the player, and for any custom meshes it will create [mesh instances](https://github.com/BabylonJS/Babylon.js/wiki/How-to-use-instances) from the original. Then as the player moves around, noa creates new voxels and instances and destroys the old ones that got too far away.

Does that help? Basically noa doesn't cull anything based on visibility, just on range. Of course, if needed you could manually delete voxels when you know the player has left that room, and add them back if they return, etc.

**Comment by andrewtheone** [comment]
Yeah, that helped thank :), what option should I tweak to set "voxel/mesh/object" loading, unloading distance?

**Comment by andyhall** [comment]
[These settings here](https://github.com/andyhall/noa-testbed/blob/master/index.js#L20-L22) :smile:
