### ISSUE TITLE
Third-person camera support?

### ISSUE THREAD

**Issue by queer** [andyhall/noa#54]
As far as I know, `noa` doesn't support this, so I tried to implement it myself. You can see what little progress I made on my fork: https://github.com/queer/noa. My solution was basically:

- Add a `thirdPerson` option
- When in third-person mode, use `BABYLON.FollowCamera` instead of `BABYLON.FreeCamera` https://github.com/queer/noa/commit/43cf935d09a11445980ebbbb5973f5ae287b2a59#diff-b749cc3d9f54b036169c5f6667c372f1R80
- Movement and rotation is all incorrect unless you add `_camera.rotationOffset = 180` to the `_camera` in `Engine.rendering`, ex https://github.com/queer/noa/commit/43cf935d09a11445980ebbbb5973f5ae287b2a59#diff-3ea7e95fe221c10d64716282fd60defdR187

At this point, most everything works correctly **execpt** for raycasting to get the block the camera is pointing at. There are a few things like camera min/max angles not being exactly correct, but that was less-important than raycasting to me. 

After digging into it more, the problem appears to be that `Engine.getCameraVector()` seemingly ends up being perpendicular to the direction the camera itself is facing in, making `Engine.pick()` return incorrect results. I tried to fix this by using the camera pitch/yaw (from `Engine.rendering.getCameraRotation()`) to construct a unit vector that faces in the correct direction, but that didn't produce the correct result either; it just gave me a vector that was still facing in the wrong direction, but with a different perpendicularity relative to the camera's actual direction. The attempts at that can be seen here: https://github.com/queer/noa/commit/43cf935d09a11445980ebbbb5973f5ae287b2a59#diff-1fdf421c05c1140f6d71444ea2b27638R397 (including some remnants of probably-misguided attempts at transforming the rotations / unit vector)

At this point I'm pretty lost as to what can be done to implement this correctly. I was wanting to open a PR if I managed to implement this successfully, but it doesn't seem like it's likely to happen.

**Comment by andyhall** [comment]
Hey, thanks for looking at the library!

Third person camera can mean a couple of things, but did you see `noa.rendering.zoomDistance`? In all my demos scrolling the mousewheel zooms the camera back by changing that property.

The way it currently works is, there's an empty mesh called `noa.rendering._cameraHolder` that stays pinned to the player's view location and rotates as the player moves their view. Then the actual camera is a child of that mesh, and when you change the `zoomDistance` the camera moves back and forth in the camera holder mesh's local coordinates, so in world coords it winds up projected to a point behind the player.

But it's meant to be an optional default implementation - a game with particular needs can in principle make a new camera and have it move however, and tell Babylon to render with that one instead of the default one. I haven't done this personally, so there might be wrinkles though.

Let me know if that's what you're looking for..

**Comment by queer** [comment]
Oh my goodness, I can't believe I didn't figure this out. Yes, this is exactly what I was wanting! Thank you so much! :heart:

**Comment by andyhall** [comment]
Ah good... the property could probably be better named.  BTW there's also a camera zoom speed property, for how fast the camera tweens to the desired zoom level. But the default behavior is that the library also raycasts backwards from the player's head each frame looking for obstructions, and limits the zoom level if it encounters solid voxels. 

Hope that helps, thanks for trying things out!
