### ISSUE TITLE
Solid Color Opacity

### ISSUE THREAD

**Issue by andrewtheone** [andyhall/noa#6]
Hey!
When I'm setting [1,1,1,0.5] as a color, without texture, it will not render the neighbouring voxel's texture as would expected.

**Comment by andrewtheone** [comment]
Edit: seems like its not only solid colors but textures, and its only a bug on the bottom face
So the block below is not rendered

**Comment by andrewtheone** [comment]
Fixed(?) opacity is handled the other way around (non-transparent: opaque-true, transparent opaque-false)

**Comment by andyhall** [comment]
Hey, I'm just catching up with your comments. This is resolved, right? I think the engine is consistent in using opacity (true=solid) rather than transparency (true=see-through). The reason is that the `opacity=false` case covers both transparent colors (where the mesh gets blended with what's behind it) and textures that are partially empty (like leaves in the demo content - no alpha blending, but some of the texture is transparent).

**Comment by andrewtheone** [comment]
Yes it is resolved, thanks :) I just got lost because of the variable name, but finally figured out

**Comment by andyhall** [comment]
Great. Remember you can close issues if they're resolved :wink:
