### ISSUE TITLE
Andy I jumped on the webpack bandwagon but issue arise 

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#69]
ok I started a hello world added an npc , blocks blah balah , but when I tried to recreate the flower 
in the colorful example it says no such thing as noa.registry.prototype.registerObjectBlock , how do I add those special types of blocks thanks

**Comment by andyhall** [comment]
Yeah, I'm afraid the colorful demo is so old that a few APIs have changed since then. Now object blocks are registered by passing a `blockMesh` parameter in the options object for registerBlock - the "test" world example [does this here](https://github.com/andyhall/noa-examples/blob/master/src/test/index.js#L102).

**Comment by andyhall** [comment]
ECS usage is documented [here](https://github.com/andyhall/ent-comp), adding a component is `noa.ents.addComponent(id, noa.ents.names.collideEntities)` or similar.

Note that the `collideEntities` component tests for collisions and fires events whenever two entities collide. It doesn't, say, apply any physics (though you can do this yourself using the callback).
