### ISSUE TITLE
Andy or EliteAsian123 question about localstorage file

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#70]
do you guys know how to share that file on forums with other players so they can try the maps ,
can we turn the locastorage file into a .txt or .json  something shareable , I cant make 100 of websites for 100 of maps ....

**Comment by andyhall** [comment]
Hi, not sure I follow the question here. Noa uses infinite worlds so the world generation needs to be a function. You mean share a file with a bunch of pre-made world data so that someone else can load it in at runtime? This could be done but the technical details would be the same as sharing data with any other web page I guess?
