### ISSUE TITLE
The further away from 0, 0, 0 I get, the more the highlight clips.

### ISSUE THREAD

**Issue by EliteAsian123** [andyhall/noa#74]
![image](https://user-images.githubusercontent.com/29520859/63869093-95a59180-c985-11e9-84b7-75c319543045.png)

Nothing else to say.

**Comment by andyhall** [comment]
Hi and great catch, I'm pretty sure this is rounding error, and conceptually it's an easy fix but I need to think a little if there's a way to do it without touching lots of different parts of the code..

**Comment by andyhall** [comment]
Hi, so this wasn't at all a simple change after all, but the newest develop branch now periodically rebases the game coordinate system to avoid precision bugs like this. It involves some pretty big changes behind the scenes, most of which shouldn't affect typical game logic. Full details are [here](https://github.com/andyhall/noa/blob/develop/doc/positions.md).

Can you try this build on your content and let me know if these changes break anything for you?

**Comment by EliteAsian123** [comment]
Hello, sorry for the late reply! I tried the dev branch on my game and the bug is fixed and everything went smoothly, except for my block breaking code which renders a "decal" over the block face, however I suspect this will be easy to fix. Thanks!

**Comment by andyhall** [comment]
Hi, thanks for checking! If you have any code directly sets mesh positions, that'll be the code that needs to change - just get the values from the various `_local` properties and things should work. Once it's placed, things should work afterwards - when the engine "rebases" the coordinates it *should* correctly move all current meshes to compensate.

But let me know if you're stuck. By the way, for testing be sure to set [originRebaseDistance](https://github.com/andyhall/noa/blob/develop/src/index.js#L50) to something small, like `5`, so that rebases happen frequently and you can confirm they're not breaking anything.

**Comment by EliteAsian123** [comment]
Hello! I've updated the decal system but the mesh seams to be shifted by 0.5 units. Here is a picture: 

![image](https://user-images.githubusercontent.com/29520859/65837958-96567e00-e2cb-11e9-8439-32af76d2153c.png)
I thought the obvious answer is to change the position of the mesh by 0.5, but the axis it is offset on is different depending on what face you are highlighting. I'm not too experienced with vector math, so I couldn't figure it out. Here is the code for handling the mesh's position:
```js
this.nppb.noa.globalToLocal(positionArray, null, this.dpos);
var dist = this.glvec3.dist(this.nppb.noa.camera._localGetPosition(), this.dpos);
var slop = 0.001 + 0.001 * dist;
for (var i = 0; i < 3; i++) {
	if (normalArray[i] === 0) {
		this.dpos[i] += 1;
        } else {
		this.dpos[i] += (normalArray[i] > 0) ? 1 + slop : -slop;
        }
}
this.mesh.position.copyFromFloats(this.dpos[0], this.dpos[1], this.dpos[2]);
this.mesh.rotation.x = (normalArray[1]) ? Math.PI / 2 : 0;
this.mesh.rotation.y = (normalArray[0]) ? Math.PI / 2 : 0;
```
And yes, I did copy the highlight's code. Sorry for bothering you!

**Comment by andyhall** [comment]
Hi, so it looks like your issue there isn't related to the position changes (if it was the mesh would be at the wrong world location, not just a half voxel off).

As for what the issue is, I can't really say without being able to test - maybe has to due with where the mesh is registered?

The things to know are, the `position` and `adjacent` properties on `noa.targetedBlock` are floored ints (that is, `adjacent` is the lower corner of the empty voxel next to the solid voxel being targeted). And similarly the `normal` property tells the direction, pointing out of the solid block. E.g. if `normal` is `[0, 1, 0]` then the normal vector points up, meaning you're targeting the top face of a solid voxel.

So, hopefully that makes it easier to see what the highlight code is doing. From your image, it looks like the mesh is positioned correctly on the normal axis (i.e. it's next to the surface of the targeted block), but it's off on the other two axes, implying maybe the wrong offset in the `(normalArray[i] === 0)` branch of the loop.

Hope that helps...

**Comment by EliteAsian123** [comment]
Hello thanks for helping me! I simply changed
```js
if (normalArray[i] === 0) {
   this.dpos[i] += 1;
} ...
```
to this:
```js
if (normalArray[i] === 0) {
   this.dpos[i] += 0.5;
} ...
```
and it work great :)

Should I close this issue or should I keep it open until the branch is merged?

Thanks!

**Comment by andyhall** [comment]
Thanks for checking the changes!
