### ISSUE TITLE
how do we add particle system to hello world example

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#77]
I tried to added but it doesnt work
var makeParticles = require('./lib/particles')
getting this error:
Module not found: Error: Can't resolve './lib/particles'

**Comment by andyhall** [comment]
There's no particle code in noa. The old demo project that code came from is [here](https://github.com/andyhall/noa-testbed/), and the particles lib it used is [here](https://github.com/andyhall/noa-testbed/blob/master/lib/particles.js). I later made it its own [library](https://github.com/andyhall/mesh-particle-system), but there may be better particle systems somewhere in the BabylonJS community.

**Comment by itzTheMeow** [comment]
I can't seem to get mesh-particle-system working. 
code:
```js
import MPS from "./mesh-particle-system.js";
import { Texture } from "../../noalib/node_modules/@babylonjs/core/Materials/Textures/texture";
var tex = new Texture("img/blocks/stone.png", scene);
var capacity = 200;
var rate = 30; // particles/second
var mps = new MPS(capacity, rate, scene);
mps.setTexture(tex);
mps.mesh.position.x = 0;
mps.mesh.position.y = 0;
mps.mesh.position.z = 0;```

this is run when a block is broken
```js
mps.setMeshPosition(pos[0], pos[1], pos[2]);
    mps.start();```

**Comment by fenomas** [comment]
Hi, unfortunately the `mesh-particle-system` library was written back before Babylon had module exports. So it assumes that the `BABYLON` object will be in global scope. You could probably use it that way if you try, but I believe that nowadays Babylon has several built-in ways of doing particles, so it would probably be easier to use those.

The only caveat is, any time you add your own mesh (e.g. the mesh for a particle system) to the Babylon scene, you'll need to call [noa.rendering.addMeshToScene](https://fenomas.github.io/noa/API/classes/lib_rendering.rendering.html#addmeshtoscene). This is because noa uses octrees to make scene mesh selection faster, and all new meshes need to be added to the octree somewhere.

**Comment by itzTheMeow** [comment]
i did put the object in global scope, but i changed the library to import everything
[mesh-particle-system.txt](https://github.com/fenomas/noa/files/7154850/mesh-particle-system.txt)

**Comment by fenomas** [comment]
In that case it should work, as long as you add:

```js
noa.rendering.addMeshToScene(mps.mesh)
```

**Comment by itzTheMeow** [comment]
here?
![image](https://user-images.githubusercontent.com/50887230/133102465-83fa1d53-494e-4d35-99e5-747e7235b62e.png)

**Comment by itzTheMeow** [comment]
renders at 0,0,0 changing a few things, thanks
