### ISSUE TITLE
Upon generating "ores", blocks are fused together.

### ISSUE THREAD

**Issue by EliteAsian123** [andyhall/noa#79]
![image](https://user-images.githubusercontent.com/29520859/64065112-64bc9b00-cbd7-11e9-80e3-f0b3c0d93dec.png)

In this game there are only two blocks, dirt and stone.
Now I know this problem exists but I'm not too sure how to fix it in this case. I used `Math.random()` at first but to get consistent results I am now using your `murmur-numbers`.

**Comment by andyhall** [comment]
I'm not sure what's going on here, is this at a chunk boundary?

If so, the thing to know is that chunks of data created in worldgen overlap by two voxels at the boundaries. If `chunkSize` is 32, then each worldgen array will be 34x34x34, and the chunks will run from [-1..32], not from [0..31]. This is done so that ambient occlusion can be done correctly at the border of a chunk without waiting for the neighbor to be created.

So the upshot is that boundary voxels - the voxel at 0,0,0, for example, will be created more than once, and to be consistent the worldgen needs to generate the same voxel id each time. The way to do that is to use `hash(x,y,z)` or similar in place of random variables. (Note that those need to world x/y/z coords, not local i/j/k coords of the voxel's position in the current chunk.)

Does that make sense? If your issue isn't at boundaries then I'll need more info.

**Comment by EliteAsian123** [comment]
Thanks for the answer! The simple fix was to replace `hash(i, j, k)` with `hash(i + x, j + y, k + z)`.
Have a good night!
