### ISSUE TITLE
Get chunk ID(s) given a specific block coordinate

### ISSUE THREAD

**Issue by raoneel** [andyhall/noa#91]
Hey, I think it would be helpful to have a function called getChunkIds(x, y, z) that is given a world coordinate and returns the chunk ids that the block could belong in.

example: getChunkIds(0,0,0) returns '0|0|0' (not sure of the exact numbers but you get the idea)

The reason it could have multiple return values is that noa has chunk overlapping, so the same block, if it's on the edge, could be in 2 chunks (maybe 4 if it's on the corner? I'm not sure).

One use case for this would be saving the state of the world. In my app, when a user places a block, I'm immediately saving it to storage which is keyed by the chunk id. When that chunk loads via worldDataNeeded, it will load all of the blocks for that chunk. BUT, if I only save the block to one chunkId, then it won't get loaded by nearby chunks if it's needed.

Example:
1. I'm in chunk 1|0|0
2. I create a block, immediately save to storage for chunk 1|0|0
3. Later, I load chunk 1|1|0, now I load from storage. I will not load the block from step 2, which I may need if it's one of those overlap blocks.

Additionally, I think this API might be helpful for other things beyond this specific use case.

Thanks!

**Comment by andyhall** [comment]
Hi, sorry for the late reply. I've been meditating on this. 

This is definitely needed, but I'm dithering over the right solution. For one, it's pretty inconvenient for you to have to store and retrieve individual voxel values, it would be better to save/restore entire chunks. But also, "chunks" are ideally meant to be an internal abstraction - e.g. I *really* don't want your game code to need to think about voxels being duplicated at chunk borders (and indeed, the engine may eventually stop doing that!).

So here's what I'm thinking. Currently, when a chunk passes out of range the engine sends an event with the chunk's raw data, which the client can compress and save for later, and the engine doesn't do anything in particular when an individual voxel id changes.

Instead, I'm thinking:

 1. When a chunk passes out of range, engine sends an event with *compressed* voxel data (e.g. run-length encoded), and a unique identifier. Client can store those wherever.
 2. When the engine requests a chunk of world data, client can *either* fill in the provided array, *or* send compressed data (that it previously received from an engine event).
 3. When an individual voxel changes, engine internally marks that chunk "dirty", and remembers that it has changed since it was last provided by the client.
 4. There's a new engine API to request storage data for all "dirty" chunks. When called, the engine emits events (similar to 1) for all chunks whose data has changed, and then marks them clean until their data changes again.

Then the use case would look like:

 1. Game client starts a new game, with no previous state
 2. Engine requests word data for chunks `1|0|0` and `1|1|0`, and client fills in data
 3. User moves around, causing `1|0|0` to get unloaded. 
 4. Engine emits event, with id `1|0|0` and some RLE data, which client can save wherever
 5. User changes a voxel (in chunk 1,1,0, but client doesn't know that), so engine internally marks that chunk dirty
 6. Game client requests data for all dirty chunks
 7. Engine emits event with id `1|1|0` and some RLE data, which client saves somewhere
 8. User quits and reloads game. This time, when engine requests `1|0|0` and `1|1|0`, client responds with saved RLE data instead of generating new data.

Make sense? This way the game client doesn't need to think about chunks or padding duplication, and also the client can control when to persist data - you could store changes every single time a voxel changes, or once per minute, or only when the user clicks "Save", etc.

I don't have persistent storage in my own game yet, so this is theoretical for me. Since you're working with this, can you think over the above and let me know if it sounds workable?

**Comment by raoneel** [comment]
Hey, thanks for the detailed reply! Your API proposal makes a lot of sense, and should work for most use cases. I particularly like how you can control when to persist data. However, I think for my specific use case, it may have some problems.

I am using your engine for a multiplayer game, so the chunk data is actually stored on a server. Furthermore, multiple people might be writing to the same chunk. If players were writing entire chunks to the server, I would run into concurrency/race conditions. Therefore, my flow is:

1. When a user places a block, send event placeBlock(x,y,z) to server
2. Server calculates what chunk this block is in, and updates a single block in that chunk.
3. Immediately send update to all clients so the block appears immediately
4. When a new player joins, they have to download all chunks. However, in step 2 if I only place the block in one chunk, I will run into issues with the padding blocks. (doing it correctly, I should store it in up to 4 chunks depending on the location of the block)

Unfortunately, it seems like I am forced to think about chunk padding in this case 😞. I think I might just write a function that calculates all the relevant chunks that need updating on the server. Ideally, for me, worldDataNeeded would not need to account for padding blocks. I wonder if it's possible to do 2 passes, and on the second pass check the chunk border stuff. I'm sure it's quite complicated though.

**Comment by andyhall** [comment]
Think this is superseded by #94, let me know if you disagree.
