### ISSUE TITLE
Non-cubic chunk size

### ISSUE THREAD

**Issue by Heath123** [andyhall/noa#97]
Is it possible to set a non-cubic chunk size? I'm trying to make a Minecraft client with this and I need to  use 16x256x16 chunks.

**Comment by andyhall** [comment]
Hi, this isn't currently possible. It could be done in principle, but there are a lot of places in the code that assume cubic chunks, so it would be a pretty fair amount of engine work.

At a guess, I'd expect that you could do this by using 16 (or 32) size cubic chunks in noa, and having some intermediate logic to cover up the difference - that is, when you receive a minecraft-sized chunk from your server, cache the data and then when noa requests a chunk, copy in data from the appropriate part of the cache. But this would be slightly hairy, since noa only requests chunk data in a spherical zone around the player, so data at the top or bottom of the minecraft world might not be requested until the player moved vertically within range of it.

Hope this helps!

**Comment by Heath123** [comment]
> Hi, this isn't currently possible. It could be done in principle, but there are a lot of places in the code that assume cubic chunks, so it would be a pretty fair amount of engine work.
> 
> At a guess, I'd expect that you could do this by using 16 (or 32) size cubic chunks in noa, and having some intermediate logic to cover up the difference - that is, when you receive a minecraft-sized chunk from your server, cache the data and then when noa requests a chunk, copy in data from the appropriate part of the cache. But this would be slightly hairy, since noa only requests chunk data in a spherical zone around the player, so data at the top or bottom of the minecraft world might not be requested until the player moved vertically within range of it.
> 
> Hope this helps!

Thank you for the advice! Maybe I can figure out a way to make noa always load in 16 chunks at a time vertically or something. What I'm doing so far is something like that, because the library I'm using stores block data and I'm loading into noa from its cache as it requests it.
Congratulations on being in an official Minecraft game by the way!

**Comment by Heath123** [comment]
Should this be closed now or should Inleave it open?

**Comment by andyhall** [comment]
Thanks for the comments, reopen or file again if you have questions!
